//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibreriasEntities : DbContext
    {
        public LibreriasEntities()
            : base("name=LibreriasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Estados> Estados { get; set; }
        public DbSet<Generos> Generos { get; set; }
        public DbSet<Historial> Historial { get; set; }
        public DbSet<libros> libros { get; set; }
        public DbSet<Marcas> Marcas { get; set; }
        public DbSet<Tercero> Tercero { get; set; }
    }
}
