//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int Id_Historial { get; set; }
        public string Id_Tercero { get; set; }
        public string Nombre_Ter { get; set; }
        public int Id_Libro { get; set; }
        public string Titulo { get; set; }
        public DateTime Fecha_Pres { get; set; }
        public DateTime Fecha_Devo { get; set; }
        public int Id_Estado { get; set; }
        public string Nom_Estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual libros libros { get; set; }
        public virtual Tercero Tercero { get; set; }
    }
}
