//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public libros()
        {
            this.Historial = new HashSet<Historial>();
        }
    
        public int Id_Libro { get; set; }
        public string Titulo { get; set; }
        public int Id_Genero { get; set; }
        public string Genero { get; set; }
        public int Id_Marca { get; set; }
        public string Marca { get; set; }
        public int Id_Estado { get; set; }
        public string Nom_Estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual ICollection<Historial> Historial { get; set; }
        public virtual Marcas Marcas { get; set; }
    }
}
