//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tercero
    {
        public Tercero()
        {
            this.Historial = new HashSet<Historial>();
        }
    
        public string Id_Tercero { get; set; }
        public string Nombre_Ter { get; set; }
        public string Apellido_Ter { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public DateTime Fecha_Nacimi { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Cuidad { get; set; }
    
        public virtual ICollection<Historial> Historial { get; set; }
    }
}
